manage/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns,  url

urlpatterns = patterns('',
    url(r'^login/$', 'manage.views.admin.login', name='manage_login'),
    url(r'^change_username/$', 'manage.views.admin.change_username', name="manage_change_username")
)

memory/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from memory import settings
from memory.forms import KSignupForm, KChangeEmailForm, KEditProfileForm, KAuthenticationForm


# handler404 = "memory.views.errors.handler404"
handler500 = "memory.views.errors.handler500"

urlpatterns = patterns("memory.views.frontend",
        url('^index/$', "index", name="home"),
        url(r'^$', "index", name='home'),
        url('^tile/(?P<tile_id>\d+)/$', "view", name='tile_view'),
        url(r'^get_user_info/$', "get_user_info", name="memory_get_user_info"), 
        url(r'^vcar/$', "vcar", name="memory_vcar"),
        url('^tile/comment/(?P<comment_id>\d+)/delete/$', "delete_comment", name='tile_delete_comment'),
)
                       
# 找回密码各项
urlpatterns += patterns("memory.views.account",
    url(r'^accounts/pwd_back_mail/$', "pwd_back_mail", name="memory_pwd_back_mail"),
    url(r'^accounts/pwd_back_mail_done/$', "pwd_back_mail_done", name="memory_pwd_back_mail_done"),
    url(r'^accounts/pwd_back_mail_reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
     'pwd_back_mail_reset',
   name='memory_pwd_back_mail_reset'),


    url(r'^accounts/pwd_back_mobile/$', "pwd_back_mobile", name="memory_pwd_back_mobile"),
    url(r'^accounts/pwd_back_mobile_get_vcode/$', "pwd_back_mobile_get_vcode", name="memory_pwd_back_mobile_get_vcode"),

    url(r'^accounts/pwd_back_pwd_reset/$', "pwd_back_pwd_reset", name="memory_pwd_back_pwd_reset"),
    url(r'^accounts/pwd_back_success/$', "pwd_back_success", name="memory_pwd_back_success"),        
)
urlpatterns += patterns('',                
    url(r'^admin/', include('memory.views.admin.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^grappelli/', include('grappelli.urls')),
    # # Edit profile
    url(r'^accounts/(?P<username>[\.\w]+)/edit/$',
       "userena.views.profile_edit", {'edit_profile_form': KEditProfileForm},
       name='userena_profile_edit'),
    url(r'^account_setting/$', 'userena.views.account_setting', name="userena_account_setting"),
    url(r'^accounts/signup/$',
       "userena.views.signup", {'signup_form': KSignupForm},
       name='userena_signup'),
    # Change email and confirm it
    url(r'^accounts/(?P<username>[\.\w]+)/email/$',
       "userena.views.email_change", {"email_form": KChangeEmailForm},
       name='userena_email_change'),
    url(r'^accounts/signin/$',
       "userena.views.signin", {"auth_form": KAuthenticationForm},
       name='userena_signin'),
    (r'^accounts/', include('userena.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^manage/', include('manage.urls')),
    (r'^photologue/', include('photologue.urls')),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/_static/img/favicon.ico'}),

)

urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

urlpatterns += patterns('memory.views.test',
    url(r'^tests/', 'test'),
)

urlpatterns += patterns('',
    # media 目录
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
        'django.views.static.serve', {"document_root": settings.MEDIA_ROOT}),
)

urlpatterns += patterns('',
    # media 目录
    url(r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:],
        'django.views.static.serve', {"document_root": settings.STATIC_ROOT}),
)

if settings.DEBUG is False:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

system/likeable/urls.py
#
# django-likeable
#
# See LICENSE for licensing details.
#

from django.conf.urls.defaults import *
from views import like_ajax, like_noajax, like_autodetect


urlpatterns = patterns('',
    url(r'^(?P<content_type_id>\d+)/(?P<object_id>\d+)', like_autodetect, name='likeable_like'),
    url(r'^noajax/(?P<content_type_id>\d+)/(?P<object_id>\d+)', like_noajax, name='likeable_noajax_like'),
    url(r'^ajax/(?P<content_type_id>\d+)/(?P<object_id>\d+)', like_ajax, name='likeable_ajax_like'),
)

system/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

memory/profiles/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from memory.validators import validate_mobile_number
from memory import helpers

from userena.models import UserenaBaseProfile
#from caching.base import CachingMixin, CachingManager
from memory import helpers
from userena import settings as userena_settings  

class Profile(UserenaBaseProfile):
    #objects = CachingManager()
    """ Default profile """
    GENDER_CHOICES = (
        (1, _('Male')),
        (2, _('Female')),
    )

    #user = models.OneToOneField(User,unique=True,verbose_name=_('User'),related_name='profile')
    user = models.ForeignKey(User,unique=True,verbose_name=_('User'),related_name='profile')

    gender = models.PositiveSmallIntegerField(_('Gender'),
                                              choices=GENDER_CHOICES,
                                              blank=True,
                                              null=True)

    # website = models.URLField(_('Website'), blank=True, verify_exists=True)
    # location =  models.CharField(_('Location'), max_length=255, blank=True)

    birth_date = models.DateField(_('Birth date'), blank=True, null=True,\
        help_text=_("Please use the following format: YYYY-MM-DD"))
    about_me = models.TextField(_('About me'), blank=True)
    mobile = models.CharField(_('Mobile'), max_length=20, blank=True, \
        validators=[validate_mobile_number])
    is_mentor = models.BooleanField(default=False, blank=False)
    is_waiter = models.BooleanField(default=False, blank=False)
    # update_username_at = models.DateField(blank=True, null=True)

    # def can_change_username(self):
        # return self.update_username_at

    # 真实姓名，解决用户的名字显示问题(学生、教师、导师)。
    realname = models.CharField(_('realname'), max_length=30, blank=True)

    @property
    def age(self):
        return helpers.calculate_age(self.birth_date)

    def chinese_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = u'%s %s' % (self.user.last_name, self.user.first_name)
        return full_name.strip()

    @property
    def is_vip(self):
        """
        目前仅判断家长身份,对推荐的瓦片进行公开的限制
        """
        try:
            self.user.student
            return True
        except Exception, e:
            return False

    @property
    def get_avatar(self):
        try:
            #self.mugshot['avatar'].url              
            return self.mugshot
        except Exception, e:           
            return helpers.get_avatar()

    def chinese_name_or_username(self):
        """
        显示的机制为 realname >> first_name,last_name >> username
        """        

        if self.realname:
            return self.realname

        user = self.user       
        
        if user.first_name or user.last_name:
            # We will return this as translated string. Maybe there are some
            # countries that first display the last name.
            name = u"%(last_name)s%(first_name)s" % \
                {'first_name': user.first_name,
                 'last_name': user.last_name}
        else:
            # Fallback to the username if usernames are used
            if not userena_settings.USERENA_WITHOUT_USERNAMES:
                name = "%(username)s" % {'username': user.username}
            else:
                name = "%(email)s" % {'email': user.email}
        
        return name.strip()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

memory/forms.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from memory.validators import memory_validate_email
from django import forms
from userena.forms import SignupForm, ChangeEmailForm, EditProfileForm, AuthenticationForm
from memory import helpers
from django.contrib.auth import authenticate
from memory.models import Tile
from django.forms import ModelForm
from captcha.fields import CaptchaField
from memory.validators import validate_mobile_number
from django.core.validators import RegexValidator
from memory.helper import verify_sms_helper

attrs_dict = {'class': 'required'}


class KSignupForm(SignupForm):
    """
    覆盖 ``userena.SignupForm``. 通过给 ``userena`` 的 view 投递``form`` 即可，操作如下::

        url(r'^accounts/signin/$',
            "userena.views.signin", {"auth_form": KAuthenticationForm},
            name='userena_signin'),

    """

    # 限定了用户名只支持英文字母和下划线.其原来支持 `.` `..` 等特殊字符.
    username = forms.RegexField(regex=r'^\w+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _('Username must contain only letters, numbers and underscores.')})

    # 增加了自定义的校验规则，不允许中文域名
    email = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Email"),
                             validators=[memory_validate_email])


class KChangeEmailForm(ChangeEmailForm):
    email = forms.CharField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Email"),
                             validators=[memory_validate_email])


class KEditProfileForm(EditProfileForm):
    """
    | 覆盖 ``userena EditProfileForm``.
    | 定义头像字段html渲染样式
    """
    def __init__(self, *args, **kwargs):
        super(KEditProfileForm, self).__init__(*args, **kwargs)
        self.fields['mugshot'].widget.template_with_initial = u'%(input)s'

    def clean_birth_date(self):
        """
        限定出生日期的范围: ``1800 ~ today ``
        """
        birth_date = self.cleaned_data['birth_date']
        return helpers.clean_birthday_rang(birth_date)


class KAuthenticationForm(AuthenticationForm):
    def clean(self):
        """
        Checks for the identification and password.

        If the combination can't be found will raise an invalid sign in error.

        ``userena`` 对用户名和 email 都是忽略大小写的，但原错误却提示不忽略大小写. 所以修改错误提示信息
        """
        identification = self.cleaned_data.get('identification')
        password = self.cleaned_data.get('password')

        if identification and password:
            user = authenticate(identification=identification, password=password)
            if user is None:
                raise forms.ValidationError(_(u"Please enter a correct username or email and password. Note that both fields are case-insensitive."))
        return self.cleaned_data

from django.db import models

class MobileForm(forms.Form):
    """
    用于找回密码的表单，有验证码
    """

    mobile = forms.CharField(max_length=20,validators=[validate_mobile_number])
    captcha = CaptchaField()

class PwdMobileForm(forms.Form):
    mobile = forms.CharField(max_length=20,validators=[validate_mobile_number])
    vcode = forms.CharField(max_length=20,validators=[RegexValidator(r'^[0-9]{6}$', u"输入一个有效的验证码", 'invalid')])

    def clean(self):
        """
        确保找到了用户，并且验证码一致
        """       

        cleaned_data = super(PwdMobileForm, self).clean()
        mobile = cleaned_data.get('mobile')
        vcode = cleaned_data.get('vcode')
        if mobile and vcode:
            user = verify_sms_helper.get_user_from_mobile(mobile)

            if user:
                server_vcode = VerifySms.objects.get_vcode(user=user)

                # 还没有生成验证码
                if not server_vcode:                                   
                    self._errors['mobile'] = self.error_class([u'尊敬的用户，请先生成验证码'])
                    del cleaned_data['mobile']          

                else:               

                    # 有验证码，比对
                    if vcode != server_vcode:
                        self._errors['vcode'] = self.error_class(['您输入的验证码不匹配，请重新录入'])
                        del cleaned_data['vcode']           
            else:
                self._errors['mobile'] = self.error_class(['这个手机号码没有关联任何用户，请检查您的手机号码是否录入正确。'])
                del cleaned_data['mobile']         
            

        return cleaned_data



class PwdResetForm(forms.Form):
    """
    密码重置
    """
    
    pwd = forms.CharField(max_length=16, min_length=6, widget=forms.PasswordInput())
    pwd_b = forms.CharField(max_length=16, min_length=6, widget=forms.PasswordInput())

    def clean(self):
        """
        验证两次密码必须一致
        """
        cleaned_data = super(PwdResetForm, self).clean()
        pwd = cleaned_data.get('pwd')
        pwd_b = cleaned_data.get('pwd_b')
        if pwd and pwd_b:
            if pwd != pwd_b:
                msg = u"两个密码不一致"

                self._errors['pwd'] = self.error_class([msg])
                self._errors['pwd_b'] = self.error_class([msg])

                del cleaned_data['pwd']
                del cleaned_data['pwd_b']

        return cleaned_data

memory/templates/userena/email_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n bootstrap %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
  <div class="nav-tabs" style="margin-bottom: 10px">
 	<h4 style="display: inline;float: left;">邮箱设置</h4>
 	<a href="{% url userena_account_setting %}" class="btn" style="display: inline;float: right;">{% trans "Back" %}</a>
 </div>
  <fieldset>
    {# <legend>{% trans "Change email address" %}</legend> #}
    {{ form|bootstrap }}
</fieldset>
<!--<p style="color:#888; font-size:14px; margin-left:177px;">系统将发送一封确认邮件到您的新邮箱，请注意查收</p>-->
<div class="form-actions">
    <input type="submit" class="btn btn-primary" value="{% trans "Change email" %}" style="margin-left:90px;" />
    <!--<a href="{% url userena_account_setting %}" class="btn" style="display: inline; margin-left:35px">{% trans "Back" %}</a>-->
</div>
</form>
<!--<div class="Kemail" style="display:none;">
    <h3 class="set-sv">登录密码修改成功</h3>
    <div class="prompt-words">
       <p class="prompt-info">你的电子邮件地址无法被验证…</p>
       <p class="prompt-info">你可以试试在帐号设置里再更改一次邮件地址。</p>
    </div>
    <p class="back-st"><a href="{% url userena_account_setting %}">点击返回账号设置界面</a></p>
</div>-->
{% endblock %}

memory/templates/userena/user_setting_form.html
{% extends 'userena/base_userena.html' %}
{% load memory_tags i18n bootstrap %}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
  <div class="nav-tabs" style="margin-bottom: 10px"><h4>帐号设置</h4></div>
  <form action="" enctype="multipart/form-data" method="post" class="form-horizontal">
  {% csrf_token %}
  <fieldset>
    <div class="control-group">
    	<label class="control-label" style="text-align:left;"><img src="{% media_path user.get_profile.get_avatar "normal" %}" id="imghead"/></label>
    	<div class="controls" style="padding-top: 50px; margin-left:160px; *margin-left:10px;">
	    	<input id="id_img_file" class="hidden" type="text" value="{{profile.mugshot}}">
	    	<a class="btn hidden" id="change_img" onclick="document.getElementById('id_mugshot').click()">修改头像</a>
	    	<input type="file" name="mugshot" class="imghidden" id="id_mugshot" onchange="previewImage(this,'imghead')">
	    </div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_username" style="width:90px;  text-align:left;">用户名</label>
        <div class="controls" style="margin-left:60px;*margin-left:-15px;">
        	{% if is_change %}
	        	<label class="control-label" style="text-align:left">{{user.username}}</label>
	        	<input id="id_username" type="hidden" name="username" maxlength="30" value="{{user.username}}">
        	{% else %}
        		<input id="id_username" type="text" name="username" maxlength="30" value="{% if ty == '1' or ty == '2' %}{{uname}}{% else %}{{user.username}}{% endif %}" onkeyup="hide_username_tip();value=value.replace(/[^\w\.\/]/ig,'')">
        		{% if ty %}
        			<div id="id_usernameTip" class="onError" style="display: inline-block; width: 250px; height: 30px; vertical-align: middle; overflow-x: visible; font-size: 12px; line-height: 12px; margin: 0px; padding: 0px; background: none repeat scroll 0% 0% transparent;"><span><span class="onError_top">{% if ty == '1' %}用户名已存在{% else %}用户名只允许字母，数字或者下划线{% endif %}</span><span class="onError_bot"></span></span></div>
        		{% endif %}
        		<script type="text/javascript">
        			function hide_username_tip(){
						document.getElementById("id_usernameTip").style.display='none';//隐藏    
					}   
				</script>
        	{% endif %}
		</div>
	</div>

	{% is_advanced_user user as is_advanced %}
	<div class="control-group" {% if is_advanced %} style="display:none"{% endif %}>
        <label class="control-label" for="id_first_name" style="width:90px;  text-align:left;">姓名</label>
        <div class="controls" style="margin-left:60px;">
            <input id="id_first_name" type="text" maxlength="30" name="first_name" 
            {% if user.first_name %} 
            	value="{{user.first_name}}" 
            {% else %} 
            	value="{{user.username}}" 
            {% endif %}>
			<div id="id_first_nameTip" style="display: inline-block;width:250px;height:30px;vertical-align:middle;overflow-x:visible; font-size: 12px; line-height: 12px;*line-height: 16px;"></div>
		</div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_gender" style="width:90px;  text-align:left;*margin-top:0px;*width:90px;">性别</label>
        <div class="controls" style="margin-left:60px;*margin-left:-15px;*width:60%;*dislplay:block; *float:left;*margin-top:-2px;">
            {{ form.gender }}
		</div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_birth_date" style="width:90px;  text-align:left;">生日</label>
        <div class="controls" style="margin-left:60px;*margin-left:-15px;">
            <input id="id_birth_date" type="text" style="*display:block; *float:left; *margin-right:7px;" name="birth_date" value="{{profile.birth_date|date:"Y-m-d"}}">
		</div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_mobile" style="width:90px;  text-align:left;">手机</label>
        <div class="controls" style="margin-left:60px;*margin-left:-15px;">
            <input id="id_mobile" type="text" maxlength="20" name="mobile" value="{{profile.mobile}}">
			<div id="id_mobileTip" style="display: inline-block;width:250px;height:30px;vertical-align:middle;overflow-x:visible; font-size: 12px; line-height: 12px;*line-height: 16px;"></div>
		</div>
	</div>
	<div class="control-group required" style="*margin-top:-20px;">
		<label class="control-label" for="id_privacy" style="width:90px;  text-align:left;">隐私设置</label>
		<div class="controls" style="margin-left:60px;">
			<div style="display:block; float:left;*margin-left:-15px; *margin-right:7px;">{{form.privacy}}</div>
		</div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_email" style="width:90px;  text-align:left;">电子邮箱</label>
        <div class="controls" style="margin-left:60px;*display:block; margin-left:-15px;*float:left;">
        	<label class="control-label e-mailset">{{user.email}}</label>
            <!--input id="id_email" type="text" maxlength="75" name="email" value="{{user.email}}" readonly="True"-->
        	<a class="btn" style="margin-left:11px;" href="{% url userena_email_change user.username %}">修改邮箱</a>
		</div>
	</div>
	<div class="control-group">
        <label class="control-label" for="id_password" style="width:90px;  text-align:left;">密码设置</label>
        <div class="controls" style="margin-left:60px;*display:block; margin-left:-15px;*float:left;">
        	<a class="btn" href="{% url userena_password_change user.username %}">修改密码</a>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_about_me" style="width:90px;  text-align:left;">关于我</label>
		<div class="controls" style="margin-left:60px; *margin-left:-8px; *display:block; *float:left;">
		<textarea id="id_about_me" class="xlarge" name="about_me" cols="40" rows="10" style="height:55px; resize:none;">{{profile.about_me}}</textarea>
		<div id="id_about_meTip" style="display: inline-block;width:250px;height:30px;vertical-align:middle;overflow-x:visible; font-size: 12px; line-height: 12px;*line-height: 16px;"></div>
		</div>
	</div>
  </fieldset>  
    <div class="form-actions">
      <input type="submit" class="btn btn-primary" value="{% trans "Save changes" %}" />
    </div>
</form>
<style>
	#id_mugshot{width:220px;font-size:14px;}
</style>
{% endblock %}
{% block extra_js %}
<script src="{{ STATIC_URL }}memory/plugins/formValidator-4.1.3.min.js"></script>
<script src="{{ STATIC_URL }}memory/plugins/formValidatorRegex.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $.formValidator.initConfig({formID:"form1",theme:"ArrowSolidBox"});
		$("#id_identification").formValidator({onFocus:"请输入邮件地址或用户名"}).inputValidator({min:1,onError:"不能为空"});
		$("#id_password").formValidator({onShow:"请输入密码",onFocus:"至少1个长度",onCorrect:"密码合法"}).inputValidator({min:1,empty:{leftEmpty:false,rightEmpty:false,emptyError:"密码两边不能有空符号"},onError:"密码不能为空,请确认"});
		if ($.browser.msie){
			 $("#id_img_file").addClass("hidden");
			 $("#change_img").addClass("hidden");
			 $("#id_mugshot").removeClass("imghidden")
		   }else{
			 $("#id_img_file").removeClass("hidden");
			 $("#change_img").removeClass("hidden");
		}  
	})

	function show_filename(){
		file_path = document.getElementById('id_mugshot').value
		var arr=file_path.split('\\');
		var my=arr[arr.length-1];
		document.getElementById('id_img_file').setAttribute("value",my)
	}
  function previewImage(file,imgId){  
           if (file.files && file.files[0]){  
               var img = document.getElementById(imgId);  
               var reader = new FileReader();  
               reader.onload = function(evt){img.src = evt.target.result;}  
               reader.readAsDataURL(file.files[0]);  
           }else{  
               file.select();  
               var src = document.selection.createRange().text;  
               $("#"+imgId).attr("src",src);
           }  
  }
</script>
{% endblock %}